Revamped examples
NetApp/terraform-provider-netapp-gcp pull request #16
Opened 2020-09-16 14:01 UTC by okrause

This PR revamps all examples heavily.

Goal is to showcase all the functionality, typical use cases and provide foundational examples for user cut/paste and customisation. It is based on typical workflows I observed by multiple users and stuff I use myself often. 

Instead of overwriting the existing examples, it creates a no examples/gcp.new folder and leaves examples/gcp intact. This is to allow review and discussion of proposed changes. Eventually, it is intended to replace the current examples.

Documentation of the individual examples can be found on the Readme.md file within examples/gcp.new and within the main resource file within each examples folder.

It also got some references to the upcoming Active Directory datasource, which was recently commited particially .

I tested all examples once or twice.

2020-09-16 16:57 UTC, suhasbshekar approved these changes

2020-09-16 17:15 UTC, lonico requested changes
looking great.  Some nitpicks

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/README.md
> +might be an expection). The tf-file named after the resource of interest in the example
exception

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/README.md
> +Change into respective folder and change provider.tf to suite your GCP project. Next look for the "locals" block in the *.tf files and customize it to fir your environment. Then run "terraform init"
typo: fir --> for

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/active_directory/minimal/active_directory.tf
> +# This example create an Active Directory entry for the specified region
create --> creates

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/active_directory/minimal/active_directory.tf
> +# until the frist SMB volume using this entry will be created
first

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/active_directory/minimal/active_directory.tf
> +}
newline missing

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/snapshot/snapshot.tf
> +# This example creates an snapshot of a volume specified via a volume data source
an --> a

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/volume/advanced/variables.tf
> +}
newline

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/volume/datasource/datasource.tf
> +}
newline
(If you're using vscode, there is a setting to always insert one)

2020-09-16 17:15 UTC, lonico commented on examples/gcp.new/volume/volume-smb/volume-smb.tf
> +  # Advise: Since SMB volumes can only be created if an Active Directory connection exists for the region,
Advice

2020-09-17 08:57 UTC, okrause commented
Fixed the typos mentioned above. Many thanks for the VScode "newline at EOF" hint. Very appreciated.

2020-09-23 05:18 UTC, merged