Document permissions required to lookup projectID
NetApp/terraform-provider-netapp-gcp pull request #58
Opened 2021-12-16 11:14 UTC by okrause

If projectID (more convenient) instead of project number is specified, the code needs additional resourcemanager.projects.get permissions, otherwise the project number lookup will fail. This doc update fixed #52.
It also adds documentation of credentials parameter.

2022-01-19 22:13 UTC, wenjun666 approved these changes

2022-01-19 22:40 UTC, lonico requested changes

2022-01-19 22:40 UTC, lonico commented on website/docs/index.html.markdown
> +  service_account = "ABSOLUT_PATH_TO_JSON_KEY_FILE"
ABSOLUTE_PATH_TO_JSON_KEY_FILE

2022-01-19 22:40 UTC, lonico commented on website/docs/index.html.markdown
> +  service_account = "ABSOLUT_PATH_TO_JSON_KEY_FILE"
This is the absolute *path*

2022-01-19 22:41 UTC, lonico commented on website/docs/index.html.markdown
> +* `service_account` - (Required) This is the *path* to a JSON key of a service account with roles/netappcloudvolume.* permissions. See [documentation].( https://cloud.google.com/architecture/partners
`This is the absolute *path*`

2022-07-27 00:39 UTC, chuyich approved these changes

2022-07-28 11:16 UTC, okrause commented
This was merged as part of #68 in 88aab01b557accdbcb041282b27dafd565f48244. Closing.

2022-07-28 11:16 UTC, closed without merging